### ISSUE TITLE
Clicking on the emoticon re-triggers the shared from 

### ISSUE THREAD

**Issue by miukumac** [kaakaa/mattermost-plugin-reacji#1]
Hi, 

After installing the plugin and activating it, we noticed that is has a minor yet a bit annoying flaw regarding clicking on the original posts emoticon as it reposts the original share.

For example:
On channel #hello you create a trigger where thumbs up shares a post to #thisisnice using a thumbs up emoticon - this works as expected, a single share is created.

However, if someone "likes" the post again later by clicking the original thumbs up again, it re-posts it to #thisisnice with the the same timestamp as before.

**Comment by kaakaa** [comment]
Thanks for reporting @miukumac ! You're right, and this issue should be fixed.

I'm going to implement the feature to keep a record that a post has been shared. When a reaction is added to a post, the post will be shared only if there is no record that it has already been shared. The record will be expired after a certain period to save storage. The default of expired period will be 30 days, and it would be configurable in system console.

How does this sounds?

---

(Another option is that embedding post_id of original post in shared post. Before sharing, searching posts with post_id of original post, and the post will be shared only if there is no posts with post_id of original post. But I supposed that this option is not stable because this option depends on the search feature, and Mattermost supports many searching system (such as MySQL, Postgres, Elasticsearch, bleve).)

**Comment by miukumac** [comment]
This sounds good to me :)

It's quite unlikely that anyone would add/press emoticons after 30 days anymore.

**Comment by kaakaa** [comment]
@miukumac Hi. I've created new release with fixes for this issue.
https://github.com/kaakaa/mattermost-plugin-reacji/releases/tag/v0.2.0

I would be glad you to try it. And if you find any problems with new release, feel free to reopen this issue or create new one. Thanks.

**Comment by miukumac** [comment]
Thank you, I will test this and let you know :)
